// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZxgW0vPX9uwHt-uuguC2OrV6zbC-KY_8',
    appId: '1:1045528557295:web:7526305b24c58d1a898d1a',
    messagingSenderId: '1045528557295',
    projectId: 'barberapp-1ef4a',
    authDomain: 'barberapp-1ef4a.firebaseapp.com',
    storageBucket: 'barberapp-1ef4a.firebasestorage.app',
    measurementId: 'G-4EDPC6D7H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOMOatAcynIP-iuc208aqt7FdONF4Kik',
    appId: '1:1045528557295:android:fcc5f39013c842ab898d1a',
    messagingSenderId: '1045528557295',
    projectId: 'barberapp-1ef4a',
    storageBucket: 'barberapp-1ef4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBndu3b0R99_q6EggkVgpJOkeVSc4qfrP8',
    appId: '1:1045528557295:ios:6ca572d0819defe5898d1a',
    messagingSenderId: '1045528557295',
    projectId: 'barberapp-1ef4a',
    storageBucket: 'barberapp-1ef4a.firebasestorage.app',
    iosBundleId: 'com.example.sharpcuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBndu3b0R99_q6EggkVgpJOkeVSc4qfrP8',
    appId: '1:1045528557295:ios:6ca572d0819defe5898d1a',
    messagingSenderId: '1045528557295',
    projectId: 'barberapp-1ef4a',
    storageBucket: 'barberapp-1ef4a.firebasestorage.app',
    iosBundleId: 'com.example.sharpcuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZxgW0vPX9uwHt-uuguC2OrV6zbC-KY_8',
    appId: '1:1045528557295:web:b2dee4ce42ac5f9d898d1a',
    messagingSenderId: '1045528557295',
    projectId: 'barberapp-1ef4a',
    authDomain: 'barberapp-1ef4a.firebaseapp.com',
    storageBucket: 'barberapp-1ef4a.firebasestorage.app',
    measurementId: 'G-DV5THGL460',
  );
}
